// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJUMXiOqO1lVPwuJLuOw2AWzPw9DV1G9g',
    appId: '1:844957699728:web:1483d9b15b0b7c38889215',
    messagingSenderId: '844957699728',
    projectId: 'authforapp-4f61e',
    authDomain: 'authforapp-4f61e.firebaseapp.com',
    storageBucket: 'authforapp-4f61e.appspot.com',
    measurementId: 'G-FM56PH2RCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2jNAfXZqKIRnQlv7JfXjyjsWpL_p1BuQ',
    appId: '1:844957699728:android:7b35fc354cb64f22889215',
    messagingSenderId: '844957699728',
    projectId: 'authforapp-4f61e',
    storageBucket: 'authforapp-4f61e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB302l96rJB3OXhP0jJhTMNxlrCguOQC6Y',
    appId: '1:844957699728:ios:6c330236ef27cf12889215',
    messagingSenderId: '844957699728',
    projectId: 'authforapp-4f61e',
    storageBucket: 'authforapp-4f61e.appspot.com',
    iosBundleId: 'com.example.authapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB302l96rJB3OXhP0jJhTMNxlrCguOQC6Y',
    appId: '1:844957699728:ios:b53987d1369b671f889215',
    messagingSenderId: '844957699728',
    projectId: 'authforapp-4f61e',
    storageBucket: 'authforapp-4f61e.appspot.com',
    iosBundleId: 'com.example.authapp.RunnerTests',
  );
}
